name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        run: actions/checkout@v6

      - name: Maven Tests
        run: mvn test

      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle